### ISSUE TITLE
Defining offsets for the file given to identify the zstd file

### ISSUE THREAD

**Issue by krum110487** [jtarchie/sqlitezstd#7]
I have a use case where I will be putting a zstd SQLite file in a Zip (with other files) where the zstd is in "Store" mode so it is not double compressed. My goal is to read the zstd directly from the Zip so it does not need to extract it.

It would be nice if there was an ```OpenWithinZip(ZipPath, ZstdFileWithinZip, flags sqlite3vfs.OpenFlag)``` function which would take a file-path to the actual SQLite file, check if it is in the zip as a "Store" compression and then store the offsets for the start and end of the file in the zip for use in the operations. If it is not in "Store" mode for that file (even if the other files are not in store compression) then it will error.

It doesn't seem like it will be too hard to implement, do you have any concerns or suggestions with this approach? I don't have time to do this anytime soon as I have other prior commitments. I am just interested in the feasibility, it seems straight forward enough.

**Comment by jtarchie** [comment]
Hey! Thanks for the request.

I took a look. The simplest solution would be to extract the file from the zip file and save it to the local file system.

With the zstd seekable format, a [`io.ReadSeeker`](https://github.com/jtarchie/sqlitezstd/blob/f29ea1c5b5db8bd2518b67aa899e2751a83da714/vfs.go#L41) is required to read the file. That is provided be `os.Open`. I don't see a way to do that with a zip file. It only provides an `io.Reader`.

Even with a `fs.Fs`, the [`File`](https://pkg.go.dev/io/fs#File) returned does not have `io.ReadSeeker`. So making the zip file look like `FS` interface wouldn't help there either.

I'm not sure there is a "straight forward" way of doing this.

I'm going to close the issue for now. If you happen to do research and find a way of doing it, please open a new issue, so we can keep track of individual discussions.
