### ISSUE TITLE
Read and Seeking within a Zip

### ISSUE THREAD

**Issue by krum110487** [jtarchie/sqlitezstd#9]
Hello,

I did a bit of research, and I think all you need is to "OpenRaw()" which returns the interface of io.Reader, but the code is as follows:

```
// OpenRaw returns a [Reader] that provides access to the [File]'s contents without
// decompression.
func (f *File) OpenRaw() (io.Reader, error) {
	bodyOffset, err := f.findBodyOffset()
	if err != nil {
		return nil, err
	}
	r := io.NewSectionReader(f.zipr, f.headerOffset+bodyOffset, int64(f.CompressedSize64))
	return r, nil
}
```

with this in mind `SectionReader` implements the `Read` and `Seek` functions which should satisfy the `ReadSeeker` implementation.

```
// SectionReader implements Read, Seek, and ReadAt on a section
// of an underlying [ReaderAt].
type SectionReader struct {
	r     ReaderAt // constant after creation
	base  int64    // constant after creation
	off   int64
	limit int64 // constant after creation
	n     int64 // constant after creation
}
```

I think it would just need to, 
1. Open the Zip, see if the file exists within 
2. Check the method for the File is 0 or "store" mode to make sure it is not compressed by the zip itself.
3. return the reader from `OpenRaw()` which is a `SectionReader`

A function like this I think will work:
```
func OpenZipDB(zipPath string, fileWithinZipPath string) (io.ReadSeeker, error) {
	z, err := zip.OpenReader(zipPath)
	if err != nil {
		return nil, err
	}

	//Loop through files and find the one we need.
	for _, f := range z.File {
		if f.Name == fileWithinZipPath {
			if f.Method != 0 {
				return nil, errors.New("database file must use store method within zip")
			}

			r, err := f.OpenRaw()
			return r.(io.ReadSeeker), err
		}
	}

	return nil, errors.New("Database was not found within zip.")
}
```

Usage:
`OpenZipDB("C:\path\to\zip.zip", "/internal/path/to/file.db")`

The only modification to your existing code would be the `Open` function, in which I would do everything like you are now. if the `os.Open` fails, then we can have a specific syntax for the Path like `zip://C:\path\to\zip#path/to/the/file.db`

this way it is like a "zip" url, which we can parse out the parts, this part is something I am not 100% sure on.

Let me know what you think or if any other functions are required, we could take the SectionReader code and add any functions to it as needed via wrapper.

**Comment by jtarchie** [comment]
Thanks for the research. When I have some time, let me take a deeper dive and see if it works.

**Comment by krum110487** [comment]
As a quick update, I have been procrastinating my real work...

The following code is untested, but it should automatically look for a valid file (not directory) using a path.

so the usage would be:
`OpenZipDB("C:/Full/Path/To/ZipFile.zip/some/internal/local/file.db")`
`OpenZipDB("/usr/Full/Path/To/ZipFile.zip/some/internal/local/file.db")`

I imagine this code would run if the normal call to open the path does not work, so that it can discover the zip by basically traversing the path to see if the "file" exists. Could make it more performant by checking if it exists as a dir along the way, but it seems to work locally.

```
func OpenZipDB(zipPath string) (io.ReadSeeker, error) {
	path, internalPath, err := findValidPath(zipPath)
	if err != nil {
		return nil, err
	}

	z, err := zip.OpenReader(path)
	if err != nil {
		return nil, err
	}

	//Loop through files and find the one we need.
	for _, f := range z.File {
		if f.Name == internalPath {
			if f.Method != 0 {
				return nil, errors.New("database file must use store method within zip")
			}

			r, err := f.OpenRaw()
			return r.(io.ReadSeeker), err
		}
	}

	return nil, errors.New("Database was not found within zip.")
}

func findValidPath(path string) (string, string, error) {
	regex := regexp.MustCompile(`[/\\]`)
	parts := regex.Split(path, -1)

	test := ""
	var err error = nil
	for _, p := range parts {
		test = filepath.Join(test, p)
		exists, inErr := fileExists(test)
		if exists {
			return test, path[len(test)+1:], nil
		}
		err = inErr
	}

	//Return the final error that occured.
	return "", "", err
}

func fileExists(filePath string) (bool, error) {
	info, err := os.Stat(filePath)
	if err == nil {
		return !info.IsDir(), nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	return false, err
}
```

**Comment by krum110487** [comment]
Alternatively, if you could add in the functionality to overwrite the open function, that would be much easier on you, and I could implement it myself. Or I can make a pull request.

**Comment by jtarchie** [comment]
After looking into it, I'm not going to support this feature.
- The VFS doesn't get parameters from `sql.Open` (a core Golang library), so another way to identify a database file within the zip file would be required.
- We cannot provide a way to "override" the `Open` function because it adheres to an interface for [vfs](https://github.com/psanford/sqlite3vfs). The `Open` function is used via the SQLite3 library under the hood; it cannot be called directly by the user, as in the proposed `OpenZipDB`.

No pull request, please; this library will not support this feature request, sorry.
